# docker-compose.yml
services:
  app:
    image: AashutoshShrestha/finance-app:latest
    container_name: finance-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env