version: "3.9"

services:
  app:
    image: yourdockerhub/finance-app:latest
    container_name: finance-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres.gyogezakjnrdoqjizqbe:M43XUPTf/Td2*eL@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
    volumes:
      - app_uploads:/app/uploads

volumes:
  app_uploads: